apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wg-overlay-service
  namespace: wireguard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wg-overlay
subjects:
- kind: ServiceAccount
  name: wg-overlay-service
  namespace: wireguard
roleRef:
  kind: ClusterRole
  name: node-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: wg-overlay
  name: wireguard-network-service
  namespace: wireguard
spec:
  selector:
    matchLabels:
      k8s-app: wg-overlay
  template:
    metadata:
      labels:
        k8s-app: wg-overlay
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      terminationGracePeriodSeconds: 0
      serviceAccountName: wg-overlay-service
      volumes:
      - name: wg-vol
        hostPath:
          path: /etc/wireguard
          type: DirectoryOrCreate
      containers:
      - name: wireguard-network-service
        image: tylloyd/wg-network-service:v20220217-a
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/wireguard
          name: wg-vol
      - name: wns-sync
        image: busybox:latest
        securityContext:
          privileged: true
        command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --pid
          - --
          - bash
          - -exc
          - |
            while :
            do
              echo "checking wireguard config ... "
              if [ -f "/etc/wireguard/update" ]; then
                echo "updating wg-quick@wg0.service"
                systemctl restart wg-quick@wg0.service
                rm /etc/wireguard/update
              else
                echo "re-sync in 5 sec"
              fi
              sleep 5
            done
      initContainers:
      - name: wireguard-init
        image: busybox:latest
        securityContext:
          privileged: true
        command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --pid
          - --
          - bash
          - -ce
          - |
            echo "Installing wireguard..."
            sudo apt update
            sudo apt install -y wireguard
            PRIVATE_KEY_FILE=/etc/wireguard/privatekey
            PUBLIC_KEY_FILE=/etc/wireguard/publickey

            if [ -f "$PRIVATE_KEY_FILE" ]; then
              echo "private key already created"
            else
              sudo wg genkey > /etc/wireguard/privatekey
            fi
            
            if [ -f "$PUBLIC_KEY_FILE" ]; then
              echo "public key already created:"
              cat /etc/wireguard/publickey
            else
              cat /etc/wireguard/privatekey | sudo wg pubkey > /etc/wireguard/publickey
            fi
            if [ -f "/etc/wireguard/wg0.conf" ]; then
              rm /etc/wireguard/wg0.conf
            fi
